---
- hosts: all
  roles:
    - ensure-tox

  tasks:
    # tox_executable var is filled by ensure-tox role
    - name: Build service api-ref
      ansible.builtin.command: "{{ tox_executable }} -e api-ref"
      args:
        chdir: "{{ zuul.projects[codegenerator_api_ref.project].src_dir }}"
      when:
        - "codegenerator_api_ref is defined"
        - "codegenerator_api_ref is mapping"
