---
- hosts: all
  roles:
    - ensure-pip
    - ensure-virtualenv

  tasks:
    - name: Install openstack-codegenerator from sources
      ansible.builtin.pip:
        chdir: "{{ zuul.projects['opendev.org/openstack/codegenerator'].src_dir }}"
        name: "."
        virtualenv: "{{ ansible_user_dir }}/.venv"

    - name: Install additional dependencies from sources
      ansible.builtin.pip:
        chdir: "{{ zuul.projects[zj_dep.project].src_dir }}"
        name: "{{ zj_dep.name }}"
        virtualenv: "{{ ansible_user_dir }}/.venv"
      loop: "{{ install_additional_projects }}"
      loop_control:
        loop_var: zj_dep

    - name: Download crate-ci/typos
      ansible.builtin.get_url:
        url: "https://github.com/crate-ci/typos/releases/download/v1.23.6/typos-v1.23.6-x86_64-unknown-linux-musl.tar.gz"
        dest: "/tmp/typos.tar.gz"

    - name: Unpack typos
      ansible.builtin.unarchive:
        src: "/tmp/typos.tar.gz"
        dest: "/usr/local/bin"
