---
- hosts: all
  roles:
    - ensure-pip
    - ensure-virtualenv

  tasks:
    - name: Install openstack-codegenerator with dependencies
      ansible.builtin.pip:
        chdir: "{{ zuul.projects['opendev.org/openstack/codegenerator'].src_dir }}"
        name: "."
        virtualenv: "{{ ansible_user_dir }}/.venv"
