---
- hosts: all
  roles:
    - ensure-pip
    - ensure-virtualenv

  tasks:
    - name: Install openstack-codegenerator with dependencies
      ansible.builtin.pip:
        name: "."
        virtualenv: "{{ ansible_user_dir }}/.venv"
