---
- hosts: all
  roles:
    - ensure-pip

  tasks:
    - name: Install openstack-codegenerator with dependencies
      ansible.buildin.pip:
        name: "."
        virtualenv: "{{ ansible_user_dir }}/.venv"
