---
- hosts: all
  tasks:
    - name: Update openapi-core
      ansible.builtin.pip:
        name: "openapi-core"
        state: "latest"
        virtualenv: "{{ ansible_user_dir }}/.venv"

    - name: Generate OpenAPI spec
      args:
        chdir: "{{ ansible_user_dir }}/.venv"
        executable: /bin/bash
      ansible.builtin.shell: |
        source {{ ansible_user_dir }}/.venv/bin/activate; openstack-codegenerator --work-dir {{ ansible_user_dir }}/wrk --target openapi-spec --service-type {{ openapi_service }}
