---
- hosts: all
  roles:
    - "ensure-rust"
  vars:
    rust_sdk_dir: "{{ ansible_user_dir }}/openstack"
  tasks:
#    - name: Generate Rust code
#      ansible.builtin.include_role:
#        name: codegenerator
#      vars:
#        codegenerator_target: "{{ zj_item.1 }}"
#        codegenerator_metadata: "{{ zj_item.0.metadata }}"
#        codegenerator_service_type: "{{ zj_item.0.service }}"
#      loop: "{{ codegenerator_service_metadata_target_map | subelements('targets') }}"
#      loop_control:
#        loop_var: zj_item

    - name: Checkout target repository
      ansible.builtin.git:
        repo: "{{ rust_sdk_git_repo }}"
        dest: "{{ rust_sdk_dir }}"

    - name: Compile
      ansible.builtin.command:
        cmd: "cargo build"
        chdir: "{{ rust_sdk_dir }}"
