---
- hosts: all
  roles:
    - "ensure-rust"
  vars:
    rust_project_dir: "{{ ansible_user_dir }}/openstack"
    rust_sdk_git_repo: "https://github.com/gtema/openstack"
  tasks:
    - name: Generate Rust code
      ansible.builtin.include_role:
        name: codegenerator
      vars:
        codegenerator_target: "{{ zj_item.1 }}"
        codegenerator_metadata: "{{ zj_item.0.metadata }}"
        codegenerator_service_type: "{{ zj_item.0.service }}"
      loop: "{{ codegenerator_service_metadata_target_map | subelements('targets') }}"
      loop_control:
        loop_var: zj_item

    - name: Checkout target repository
      ansible.builtin.git:
        repo: "{{ rust_sdk_git_repo }}"
        dest: "{{ rust_project_dir }}"

    - name: Compile
      ansible.builtin.command:
        cmd: "cargo build"
        chdir: "{{ rust_project_dir }}"

    - name: Overwrite generated files
      ansible.builtin.include_role:
        name: copy_rust_code
      vars:
        rust_targets: "{{ zj_item.targets }}"
        rust_metadata: "{{ zj_item.metadata }}"
        rust_service_type: "{{ zj_item.service }}"
      loop: "{{ codegenerator_service_metadata_target_map }}"
      loop_control:
        loop_var: zj_item

    - name: Compile
      ansible.builtin.command:
        cmd: "cargo build"
        chdir: "{{ rust_project_dir }}"

    - name: Git status
      ansible.builtin.command:
        cmd: "git status"
        chdir: "{{ rust_project_dir }}"
