---
- project:
    templates:
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py311
      #        - codegenerator-openapi-block-storage-tips-with-api-ref
      #        - codegenerator-openapi-compute-tips-with-api-ref
      #        - codegenerator-openapi-identity-tips-with-api-ref
        - codegenerator-openapi-image-tips-with-api-ref
      #        - codegenerator-openapi-load-balancing-tips-with-api-ref
      #        - codegenerator-openapi-network-tips-with-api-ref
      #        - codegenerator-openapi-object-store-static
      #        - codegenerator-openapi-placement-tips-with-api-ref
      #        - codegenerator-openapi-shared-file-system-tips-with-api-ref
        - codegenerator-tox-publish-openapi-specs
        - codegenerator-rust-all
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py311
        - codegenerator-openapi-block-storage-tips-with-api-ref
        - codegenerator-openapi-compute-tips-with-api-ref
        - codegenerator-openapi-identity-tips-with-api-ref
        - codegenerator-openapi-image-tips-with-api-ref
        - codegenerator-openapi-load-balancing-tips-with-api-ref
        - codegenerator-openapi-network-tips-with-api-ref
        - codegenerator-openapi-object-store-static
        - codegenerator-openapi-placement-tips-with-api-ref
        - codegenerator-openapi-shared-file-system-tips-with-api-ref
        - codegenerator-tox-publish-openapi-specs
        - codegenerator-rust-all
