---
- project:
    templates:
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py311
        - codegenerator-openapi-compute-api-ref-tips
